
record state {
    wrk   : list<float64>,
}

record chiresult {
    df     : float64,
    chisq  : float64,
    pvalue : float64, 
}

chisq-init  : func() -> state
chisq-iter  : func(st: state, nr: s64, nc: s64, cell: float64, rt: float64, ct: float64) -> state
chisq-merge : func(st1: state, st2: state) -> state
chisq-term  : func(st: state) -> chiresult

